//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wa_Cuestionarios
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUsuarios
    {
        public System.Guid UsuarioID { get; set; }
        public int TipoUsuarioID { get; set; }
        public int PerfilID { get; set; }
        public string CodigoUsuario { get; set; }
        public string Usuario { get; set; }
        public string Clave { get; set; }
        public string Nombres { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public Nullable<int> GeneroID { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public string CorreoPersonal { get; set; }
        public string CorreInstitucional { get; set; }
        public string Celular { get; set; }
        public string TelefonoContacto { get; set; }
        public Nullable<System.Guid> UbicacionID { get; set; }
        public string CodigoPromo { get; set; }
        public int EstatusRegistroID { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public Nullable<System.Guid> CorporativoID { get; set; }
    
        public virtual catGenero catGenero { get; set; }
    }
}
