//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wa_Cuestionarios
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUbicaciones
    {
        public System.Guid UbicacionID { get; set; }
        public Nullable<int> TipoUbicacionID { get; set; }
        public string CalleNumero { get; set; }
        public string CodigoPostal { get; set; }
        public string ColoniaID { get; set; }
        public int EstatusRegistroID { get; set; }
        public System.DateTime FechaRegistro { get; set; }
    
        public virtual tblMexCP tblMexCP { get; set; }
    }
}
